# Setup
title:        DeepFault
tagline:      Fault Localization For Deep Neural Networks
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author1:
  name:       H. Ferit Eniser
  url:        https://hasanferit.github.com 

author2:
  name:       Simos Gerasimou
  url:        https://www-users.cs.york.ac.uk/~simos/

author3:
  name:       Alper Sen
  url:        https://www.cmpe.boun.edu.tr/~sen/

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown